# Site settings
title: My Blog!
email: david.r.rivera193@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm David, Node.js developer, Android developer, and
  i love working on opensource projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_url: https://twitter.com/duhruh
github_url:  https://github.com/davidrivera/
linkedin_url: https://www.linkedin.com/pub/david-rivera/82/995/797
gravatar_url: http://www.gravatar.com/avatar/53c3e800211ecbf9e38c588f993c128e

# Build settings
markdown: kramdown
